### ISSUE TITLE
runtime/cgo: pthread_create failed: Operation not permitted

### ISSUE THREAD

**Issue by dragonTour** [pixie-io/pixie#1101]
**Describe the bug*
cloud uses the latest image, and pods report errors

**Logs**
```
[root@xxx]# kubectl logs api-server-67dff56579-8v8z6 -n plc
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x7f37e2e9ea7c m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0x7f37e2e9ea7c
stack: frame={sp:0x7ffedd91d170, fp:0x0} stack=[0x7ffedd11e6f0,0x7ffedd91d700)
0x00007ffedd91d070:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d080:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d090:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0a0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0b0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0c0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0d0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0e0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0f0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d100:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d110:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d120:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d130:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d140:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d150:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d160:  0x0000000000000000  0x00007f37e2e9ea6e 
0x00007ffedd91d170: <0x0000000000000000  0x0000000000000000 
0x00007ffedd91d180:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d190:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d1a0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d1b0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d1c0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d1d0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d1e0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d1f0:  0x0000000000000000  0x6b7ec8032973f000 
0x00007ffedd91d200:  0x00007f37e2e05740  0x0000000000000006 
0x00007ffedd91d210:  0x0000000003aee2e0  0x0000000000000178 
0x00007ffedd91d220:  0x0000000002f90320  0x00007f37e2e4a476 
0x00007ffedd91d230:  0x00007f37e3022e90  0x00007f37e2e307f3 
0x00007ffedd91d240:  0x0000000000000020  0x0000000000000000 
0x00007ffedd91d250:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d260:  0x0000000000000000  0x0000000000000000 
runtime: g 0: unknown pc 0x7f37e2e9ea7c
stack: frame={sp:0x7ffedd91d170, fp:0x0} stack=[0x7ffedd11e6f0,0x7ffedd91d700)
0x00007ffedd91d070:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d080:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d090:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0a0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0b0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0c0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0d0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0e0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d0f0:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d100:  0x0000000000000000  0x0000000000000000 
0x00007ffedd91d110:  0x0000000000000000  0x0000000000000000 
...
```

```
- Pixie version: latest
- K8s cluster version: 1.23
- Node Kernel version: 4.18

**Comment by JamesMBartlett** [comment]
Hi there! Could you please list the steps you followed to reproduce this issue? Also in the future, please follow our bug report issue template.

**Comment by dragonTour** [comment]
**To Reproduce**
Steps to reproduce the behavior:

1.run on my own infrastructure with the following self-managed option.
```
[root@xxx pixie]# git clone https://github.com/pixie-io/pixie.git
[root@xxx pixie]# cd pixie
[root@xxx pixie]# export LATEST_CLOUD_RELEASE=$(git tag | grep 'release/cloud'  | sort -r | head -n 1 | awk -F/ '{print $NF}')
[root@xxx pixie]# git checkout "release/cloud/prod/${LATEST_CLOUD_RELEASE}"
[root@xxx pixie]# git checkout "release/cloud/prod/${LATEST_CLOUD_RELEASE}"
error: pathspec 'release/cloud/prod/1679419561' did not match any file(s) known to git.
```

2. Then,change to install Pixie in an air gapped environment
```
1. mkcert -install
2. kubectl create namespace plc && ./scripts/create_cloud_secrets.sh
3. curl https://storage.googleapis.com/pixie-dev-public/cloud/latest/pixie_cloud.tar.gz | tar xj
4. remove the plugin-db-updater-job job in pixie_cloud/yamls/cloud.yaml
5. kubectl apply -f yamls/cloud_deps_elastic_operator.yaml
6. modify yamls/cloud_deps.yaml to specify the storageClassName,
7. kubectl apply -f yamls/cloud_deps.yam
8. kubectl apply -f yamls/cloud.yaml
```
**Expected behavior**
The Air Gapped Pixie way goes to step 8 above，
except for kratos, clodu-proxy pods do not report errors, and the rest of the pods will report errors

**Logs**
```
[root@xxx pixie_cloud]# kubectl get po -n plc
NAME                                      READY   STATUS             RESTARTS       AGE
api-server-54b8b6475f-2klqz               0/1     CrashLoopBackOff   6 (92s ago)    7m43s
artifact-tracker-server-df468f495-65z54   0/1     CrashLoopBackOff   6 (103s ago)   7m43s
auth-server-5c7ccfcb98-r79k2              0/1     CrashLoopBackOff   6 (111s ago)   7m43s
cloud-proxy-567944bc8-4wdls               1/2     CrashLoopBackOff   6 (111s ago)   7m42s
config-manager-server-7dd897b65b-sbzh6    0/1     CrashLoopBackOff   6 (2m1s ago)   7m42s
cron-script-server-6cfcb56bdd-lhfb8       0/1     CrashLoopBackOff   6 (118s ago)   7m41s
hydra-6496d8d76-7gxx2                     1/2     CrashLoopBackOff   6 (101s ago)   7m41s
indexer-server-86f856dbf9-s6n69           0/1     CrashLoopBackOff   6 (88s ago)    7m41s
kratos-5fdb85995c-cx85m                   2/2     Running            0              7m41s
metrics-server-64cc8f6944-4pzsq           0/1     CrashLoopBackOff   6 (97s ago)    7m40s
pl-elastic-es-data-0                      1/1     Running            0              9m47s
pl-elastic-es-master-0                    1/1     Running            0              9m47s
pl-elastic-es-master-1                    1/1     Running            0              9m47s
pl-nats-0                                 1/1     Running            0              9m51s
pl-nats-1                                 1/1     Running            0              9m30s
pl-nats-2                                 1/1     Running            0              9m8s
plugin-server-569c8cf5d4-2lnxk            0/1     CrashLoopBackOff   6 (117s ago)   7m40s
postgres-6f75677777-7q284                 1/1     Running            0              9m51s
profile-server-fd5c7c7bf-hrhnr            0/1     CrashLoopBackOff   6 (111s ago)   7m40s
project-manager-server-67bd47d4f6-vs8mw   0/1     CrashLoopBackOff   6 (112s ago)   7m39s
scriptmgr-server-654f96d545-lkwqc         0/1     CrashLoopBackOff   6 (106s ago)   7m39s
vzconn-server-6d5c49fb79-6f8zw            0/1     CrashLoopBackOff   6 (97s ago)    7m39s
vzmgr-server-69f698c9c8-flnms             0/1     CrashLoopBackOff   6 (89s ago)    7m39s
```
```
[root@host-10-19-37-87 pixie_cloud]# kubectl logs api-server-54b8b6475f-2klqz -n plc
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x7fae985fba7c m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0x7fae985fba7c
stack: frame={sp:0x7ffd2b29dfa0, fp:0x0} stack=[0x7ffd2aa9f520,0x7ffd2b29e530)
0x00007ffd2b29dea0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29deb0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dec0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29ded0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dee0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29def0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df00:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df10:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df20:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df30:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df40:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df50:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df60:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df70:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df80:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df90:  0x0000000000000000  0x00007fae985fba6e 
0x00007ffd2b29dfa0: <0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dfb0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dfc0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dfd0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dfe0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dff0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29e000:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29e010:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29e020:  0x0000000000000000  0x7646fa97fe02ce00 
0x00007ffd2b29e030:  0x00007fae98562740  0x0000000000000006 
0x00007ffd2b29e040:  0x0000000004e352e0  0x0000000000000178 
0x00007ffd2b29e050:  0x0000000002f90320  0x00007fae985a7476 
0x00007ffd2b29e060:  0x00007fae9877fe90  0x00007fae9858d7f3 
0x00007ffd2b29e070:  0x0000000000000020  0x0000000000000000 
0x00007ffd2b29e080:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29e090:  0x0000000000000000  0x0000000000000000 
runtime: g 0: unknown pc 0x7fae985fba7c
stack: frame={sp:0x7ffd2b29dfa0, fp:0x0} stack=[0x7ffd2aa9f520,0x7ffd2b29e530)
0x00007ffd2b29dea0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29deb0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dec0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29ded0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dee0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29def0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df00:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df10:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df20:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df30:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df40:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df50:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df60:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df70:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df80:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29df90:  0x0000000000000000  0x00007fae985fba6e 
0x00007ffd2b29dfa0: <0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dfb0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dfc0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dfd0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dfe0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29dff0:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29e000:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29e010:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29e020:  0x0000000000000000  0x7646fa97fe02ce00 
0x00007ffd2b29e030:  0x00007fae98562740  0x0000000000000006 
0x00007ffd2b29e040:  0x0000000004e352e0  0x0000000000000178 
0x00007ffd2b29e050:  0x0000000002f90320  0x00007fae985a7476 
0x00007ffd2b29e060:  0x00007fae9877fe90  0x00007fae9858d7f3 
0x00007ffd2b29e070:  0x0000000000000020  0x0000000000000000 
0x00007ffd2b29e080:  0x0000000000000000  0x0000000000000000 
0x00007ffd2b29e090:  0x0000000000000000  0x0000000000000000 

goroutine 1 [running]:
runtime.systemstack_switch()
        GOROOT/src/runtime/asm_amd64.s:459 fp=0xc000088780 sp=0xc000088778 pc=0x46b700
runtime.main()
        GOROOT/src/runtime/proc.go:170 +0x6d fp=0xc0000887e0 sp=0xc000088780 pc=0x43bd8d
runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000887e8 sp=0xc0000887e0 pc=0x46d921

rax    0x0
rbx    0x7fae98562740
rcx    0x7fae985fba7c
rdx    0x6
rdi    0x1
rsi    0x1
rbp    0x1
rsp    0x7ffd2b29dfa0
r8     0x7ffd2b29e070
r9     0x7fffffff
r10    0x8
r11    0x246
r12    0x6
r13    0x16
r14    0x2f90320
r15    0x7fae711f135b
rip    0x7fae985fba7c
rflags 0x246
cs     0x33
fs     0x0[root@xxx pixie_cloud]# kubectl logs vzconn-server-6d5c49fb79-6f8zw -n plc
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x7f51f63a4a7c m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0x7f51f63a4a7c
stack: frame={sp:0x7fff38f29b40, fp:0x0} stack=[0x7fff3872b0c0,0x7fff38f2a0d0)
0x00007fff38f29a40:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29a50:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29a60:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29a70:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29a80:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29a90:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29aa0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29ab0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29ac0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29ad0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29ae0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29af0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b00:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b10:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b20:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b30:  0x0000000000000000  0x00007f51f63a4a6e 
0x00007fff38f29b40: <0x0000000000000000  0x0000000000000000 
0x00007fff38f29b50:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b60:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b70:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b80:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b90:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29ba0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29bb0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29bc0:  0x0000000000000000  0x12d8788e98eedf00 
0x00007fff38f29bd0:  0x00007f51f630b740  0x0000000000000006 
0x00007fff38f29be0:  0x00000000043df2e0  0x0000000000000178 
0x00007fff38f29bf0:  0x00000000025d1b60  0x00007f51f6350476 
0x00007fff38f29c00:  0x00007f51f6528e90  0x00007f51f63367f3 
0x00007fff38f29c10:  0x0000000000000020  0x0000000000000000 
0x00007fff38f29c20:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29c30:  0x0000000000000000  0x0000000000000000 
runtime: g 0: unknown pc 0x7f51f63a4a7c
stack: frame={sp:0x7fff38f29b40, fp:0x0} stack=[0x7fff3872b0c0,0x7fff38f2a0d0)
0x00007fff38f29a40:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29a50:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29a60:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29a70:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29a80:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29a90:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29aa0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29ab0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29ac0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29ad0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29ae0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29af0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b00:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b10:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b20:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b30:  0x0000000000000000  0x00007f51f63a4a6e 
0x00007fff38f29b40: <0x0000000000000000  0x0000000000000000 
0x00007fff38f29b50:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b60:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b70:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b80:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29b90:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29ba0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29bb0:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29bc0:  0x0000000000000000  0x12d8788e98eedf00 
0x00007fff38f29bd0:  0x00007f51f630b740  0x0000000000000006 
0x00007fff38f29be0:  0x00000000043df2e0  0x0000000000000178 
0x00007fff38f29bf0:  0x00000000025d1b60  0x00007f51f6350476 
0x00007fff38f29c00:  0x00007f51f6528e90  0x00007f51f63367f3 
0x00007fff38f29c10:  0x0000000000000020  0x0000000000000000 
0x00007fff38f29c20:  0x0000000000000000  0x0000000000000000 
0x00007fff38f29c30:  0x0000000000000000  0x0000000000000000 

goroutine 1 [running]:
runtime.systemstack_switch()
        GOROOT/src/runtime/asm_amd64.s:459 fp=0xc000076780 sp=0xc000076778 pc=0x46b320
runtime.main()
        GOROOT/src/runtime/proc.go:170 +0x6d fp=0xc0000767e0 sp=0xc000076780 pc=0x43bd8d
runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000767e8 sp=0xc0000767e0 pc=0x46d541

rax    0x0
rbx    0x7f51f630b740
rcx    0x7f51f63a4a7c
rdx    0x6
rdi    0x1
rsi    0x1
rbp    0x1
rsp    0x7fff38f29b40
r8     0x7fff38f29c10
r9     0x7fffffff
r10    0x8
r11    0x246
r12    0x6
r13    0x16
r14    0x25d1b60
r15    0x7f51cef9a35b
rip    0x7f51f63a4a7c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0gs     0x0
```

```

```

**Comment by vihangm** [comment]
Hey @dragonTour I believe this is the same as https://github.com/actions/runner-images/issues/3812
I could repro a similar issue with a docker runtime `20.10.8` but not with docker runtime version `20.10.12`

Can you upgrade your docker and try again?

**Comment by wenhuwang** [comment]
I have same issues.
```
~ k -n plc get pods
NAME                                       READY   STATUS             RESTARTS         AGE
api-server-7fd9998975-glb6p                0/1     CrashLoopBackOff   8 (89s ago)      17m
artifact-tracker-server-66cdcfcc59-tvnfv   0/1     CrashLoopBackOff   11 (2m13s ago)   34m
auth-server-9fd49c5d-j8qrf                 0/1     CrashLoopBackOff   11 (89s ago)     34m
cloud-proxy-7f54d7c4cf-pfdz6               1/2     CrashLoopBackOff   15 (32s ago)     34m
config-manager-server-6d96f647cb-6cnfp     0/1     CrashLoopBackOff   11 (2m7s ago)    34m
cron-script-server-769b97f44-dwgwn         0/1     CrashLoopBackOff   11 (116s ago)    34m
hydra-db8744797-dxw75                      2/2     Running            0                34m
indexer-server-ff45646f9-gk8sq             0/1     CrashLoopBackOff   11 (89s ago)     34m
kratos-5d9f7cc46c-t7qz6                    2/2     Running            0                32m
metrics-server-d4687d6b6-xsltp             0/1     CrashLoopBackOff   11 (114s ago)    34m
pl-elastic-es-data-0                       1/1     Running            0                3h15m
pl-elastic-es-master-0                     1/1     Running            0                3h15m
pl-elastic-es-master-1                     1/1     Running            0                3h15m
pl-nats-0                                  1/1     Running            0                3h7m
pl-nats-1                                  1/1     Running            0                3h7m
pl-nats-2                                  1/1     Running            0                3h7m
plugin-server-7f97f658d8-s84fs             0/1     CrashLoopBackOff   11 (2m9s ago)    34m
postgres-6d79447d-4svnd                    1/1     Running            0                22h
profile-server-77f68bfc4f-67dbh            0/1     CrashLoopBackOff   11 (2m52s ago)   34m
project-manager-server-64bf99948b-pss9c    0/1     CrashLoopBackOff   11 (2m36s ago)   34m
scriptmgr-server-6b75778c7c-mr76x          0/1     CrashLoopBackOff   11 (118s ago)    34m
vzconn-server-c8768686f-kr254              0/1     CrashLoopBackOff   11 (98s ago)     34m
vzmgr-server-68ccc894c8-xn5nk              0/1     CrashLoopBackOff   11 (101s ago)    34m
```

Env:
- Pixie cloud version: 0.1.6
- K8s cluster version : v1.22.2
- Node Kernel version: 5.4.207-1.el7.elrepo.x86_64
- os: CentOS Linux 7 (Core)
- container runtime version:   containerd://1.4.4

**Comment by AsherAroussi** [comment]
Is there any resolution for this issue ?
I install docker 20.10.12 as suggested here but still got this error.
Pixie cloud version: 0.1.7
k8s server version: 1.20
k8s client version: 1.27
OS: Ubuntu 18.04

**Comment by tanjunchen** [comment]
I have the same question with the piexi commit 1e70a528ef05.
The Env are
```
Pixie cloud version: latest
k8s server version: v1.22.5
Runtime: docker://20.10.5
OS: Ubuntu 20.04 LTS
Kernel: 5.4.0-139-generic
```

**Comment by AsherAroussi** [comment]
What fixes for me this issue is to define the seccomp profile from Runtime to Unconfined

**Comment by tanjunchen** [comment]
> I have the same question with the piexi commit 1e70a528ef05. The Env are
> 
> ```
> Pixie cloud version: latest
> k8s server version: v1.22.5
> Runtime: docker://20.10.5
> OS: Ubuntu 20.04 LTS
> Kernel: 5.4.0-139-generic
> ```

I have resolved it by using containerd not using docker://20.10.5.
