### ISSUE TITLE
[BUG] UI crashed in self hosted pixie cloud

### ISSUE THREAD

**Issue by domechn** [pixie-io/pixie#348]
**Describe the bug**

ui creashed when clicking the "Admin" Button (self hosted plc)

![image](https://user-images.githubusercontent.com/31119455/140472585-3467a072-819e-44d4-b182-2dfb7961ef02.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/31119455/140472528-91efc5bc-45dd-497b-b19a-e3a746a8863d.png)

**Logs**

```
Cannot destructure property 'embedState' of 'i.useContext(...)' as it is null.
    in Unknown
    in Jn
    in div
    in eo
    in to
    in t
    in t
    in ro
    in t
    in t
    in Zu
    in t
    in t
    in div
    in t
    in C
    in Ed
    in Unknown
    in ForwardRef
    in l
    in Ei
    in d
    in l
    in f
    in wd
    in ie
    in _r
    in s
    in Ed

Raw error:
  at TypeError: Cannot destructure property 'embedState' of 'i.useContext(...)' as it is null.
  at     at https://pixie.local.dev/static/main.3a4576a542a367220952.js:213:17597
  at     at Xo (https://pixie.local.dev/static/vendor.009f72be365e30d37d87.js:101:432776)
  at     at La (https://pixie.local.dev/static/vendor.009f72be365e30d37d87.js:101:441625)
  at     at ja (https://pixie.local.dev/static/vendor.009f72be365e30d37d87.js:101:441444)
  at     at Ma (https://pixie.local.dev/static/vendor.009f72be365e30d37d87.js:101:441127)
  at     at vs (https://pixie.local.dev/static/vendor.009f72be365e30d37d87.js:101:482209)
  at     at fu (https://pixie.local.dev/static/vendor.009f72be365e30d37d87.js:101:471457)
  at     at gu (https://pixie.local.dev/static/vendor.009f72be365e30d37d87.js:101:471382)
  at     at ru (https://pixie.local.dev/static/vendor.009f72be365e30d37d87.js:101:468412)
  at     at https://pixie.local.dev/static/vendor.009f72be365e30d37d87.js:101:420191
```

**App information (please complete the following information):**
- Pixie Cloud version: 1636161793 (image tag), pulled at 2021-11-05
- K8s cluster version: 1.18.20-eks

**Additional context**

**Comment by NickLanam** [comment]
Fixed in [6f0c8d0](https://github.com/pixie-io/pixie/commit/6f0c8d0b240c4bd4511d9acd0b4b44652d74abb2). It originally broke in [77a3e3c](https://github.com/pixie-io/pixie/commit/77a3e3cb45bf12a98adef19b0eaa5178dcc84f27#diff-ff939279328691a61a7a429583a879d3b22a20dc3959244c8dc31832525801f6R161) due to an oversight on my part when reviewing. Sorry about that!
