### ISSUE TITLE
Self-Hosted - Pixie UI Crash when update to newest image tag

### ISSUE THREAD

**Issue by dontmint** [pixie-io/pixie#572]
**Describe the bug**

I have followed [this guide](https://github.com/pixie-io/pixie/issues/266) to install Pixie Sefl-Hosted in an air gap environment, the first try was a success.
But when I reinstall again or restart our components, docker tries to fetch the newest image since tags are `latest` and the UI crash when I logged in the first time.

I believe the working version is **1657049209** for all the components under [Pixie OSS Cloud repo](https://console.cloud.google.com/gcr/images/pixie-oss/global/pixie-prod/cloud). Everything works fine again after I replace 

```
gcr.io/pixie-oss/pixie-prod/cloud/{component-name}_image:latest
--->
gcr.io/pixie-oss/pixie-prod/cloud/{component-name}_image:1657049209
```

**To Reproduce**
1. Follow [this guide ](https://github.com/pixie-io/pixie/issues/266)
2. Create password for default user
3. Login into the Pixie UI

**Expected behavior**
Login success and UI don't crash

**Screenshots**
![Screen Shot 2022-08-18 at 15 10 41](https://user-images.githubusercontent.com/34891994/185345852-ad190d25-4cbf-4c9a-be4e-8941cc80561a.png)

**Logs**

```
Unexpected end of JSON input
    at https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:14:20888
    at LiveWithProvider
    at t (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:523972)
    at t (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:524598)
    at Ng (https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:423:342)
    at t (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:523972)
    at t (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:524598)
    at t (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:521315)
    at Gt (https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:14:14453)
    at CC (https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:454:53532)
    at vC (https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:454:57145)
    at s (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:5631916)
    at https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:14:13786
    at wC (https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:454:58061)
    at g (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:119126)
    at l (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:118844)
    at h (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:119246)
    at https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:346:24543
    at https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:346:25380
    at https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:8:4754
    at https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:1:114429
    at a (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:73349)
    at CC (https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:454:53532)

Raw error:
  at SyntaxError: Unexpected end of JSON input
  at     at JSON.parse (<anonymous>)
  at     at https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:22:233
  at     at https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:22:680
  at     at https://work.pixie.example.com/static/main.191f02bec54ff54a8d56.js:22:1258
  at     at eu (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:355687)
  at     at Il (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:375999)
  at     at https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:372654
  at     at b (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:4017832)
  at     at MessagePort.D (https://work.pixie.example.com/static/vendor.b75fcbc77287c65ed2f6.js:147:4018364)
```

**App information (please complete the following information):**
- Pixie version: latest
- K8s cluster version: 1.20
- Node Kernel version: 5.4.10
- Browser version: Microsoft Edge 104.0.1293.54 (also Chrome, Firefox, Safari latest update)

**Additional context**

**Comment by philkuz** [comment]
Did you try a hard refresh of your UI (CTRL/CMD + shift + R)? Sometimes cache keeps around an old version.

**Comment by dontmint** [comment]
Hi @philkuz 
Yes, I did that many times for each browser I tested, clear all caches and cookies in Developer Mode. Removed and reinstalled Pixie still came up with the same result.

**Comment by zasgar** [comment]
@aimichelle , can you see if you can repro this?

**Comment by aimichelle** [comment]
Hi @dontmint , just wanted to check back in. Are you still running into this on the latest version of the cloud? Thank you!

**Comment by dontmint** [comment]
Last time I checked the Pixie UI was good, I think the problem is fixed, closed this Issue now. Thanks @aimichelle and the team.
