### ISSUE TITLE
r.customizeRetentionScript is not a function

### ISSUE THREAD

**Issue by mickeyzzc** [pixie-io/pixie#662]
**Describe the bug**
r.customizeRetentionScript) is not a function

**Screenshots**
![image](https://user-images.githubusercontent.com/1990362/205194220-6afbd3f6-a8d0-46f2-ae8d-50f815a30182.png)

```
(0 , r.customizeRetentionScript) is not a function
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:370:59402
    at tbody
    at https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:2:355
    at https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:19306
    at table
    at https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:2:355
    at https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:18150
    at div
    at https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:2:355
    at https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:2:76836
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:370:62542
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:370:10660
    at div
    at https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:2:355
    at https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:2:76836
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:370:63563
    at t (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:523995)
    at t (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:524621)
    at t (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:523995)
    at div
    at div
    at div
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:378:522
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:378:1375
    at t (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:523995)
    at t (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:524621)
    at Ag (https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:424:342)
    at t (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:523995)
    at t (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:524621)
    at t (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:521338)
    at Xt (https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:14:15636)
    at zC (https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:455:50883)
    at FC (https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:455:54496)
    at s (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:5519959)
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:14:14969
    at BC (https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:455:55412)
    at g (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:119149)
    at u (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:118867)
    at h (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:119269)
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:347:24543
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:347:25380
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:8:5629
    at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:1:119653
    at a (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:73369)
    at zC (https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:455:50883)

Raw error:
  at TypeError: (0 , r.customizeRetentionScript) is not a function
  at     at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:211:634
  at     at Object.useMemo (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:331651)
  at     at t.useMemo (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:3874614)
  at     at $n (https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:211:560)
  at     at https://work.dev.withpixie.dev/static/main.60db645b558cd3b9e79a.js:370:59630
  at     at As (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:325282)
  at     at ka (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:346151)
  at     at Sa (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:345359)
  at     at wa (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:344964)
  at     at Al (https://work.dev.withpixie.dev/static/vendor.1736c2f6e990f0f29fe3.js:147:385872)
```

**Comment by aimichelle** [comment]
Fixed by a48166b052ab575e863e04b64e5cc5f813adfa8c. Please check out the latest release (cloud/prod/1672961079) and let us know if you continue to run into any issues!
