### ISSUE TITLE
Online Boutique demo deployed with px CLI in CrashLoopBackOff

### ISSUE THREAD

**Issue by bpschmitt** [pixie-io/pixie#689]
**Describe the bug**

Two services in the Online Boutique demo deployed using `px demo deploy px-online-boutique` are in CrashLoopBackOff with the following errors:

`emailservice`

```
Profiler enabled.
Tracing enabled.
Debugger enabled.
{"severity":"info","time":1673536345440,"pid":1,"hostname":"currencyservice-5c7f7b6ddf-hxzh2","name":"currencyservice-server","message":"Starting gRPC server on port 7000...","v":1}
(node:1) [changeLevelName_deprecation] Warning: The changeLevelName option is deprecated and will be removed in v7. Use levelKey instead.
(Use `node --trace-warnings ...` to show where the warning was created)
{"severity":"info","time":1673536345539,"pid":1,"hostname":"currencyservice-5c7f7b6ddf-hxzh2","name":"currencyservice-server","message":"CurrencyService gRPC server started on port 7000","v":1}
/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120
        throw new Error('Project ID must be specified in the configuration');
              ^

Error: Project ID must be specified in the configuration
    at initConfigMetadata (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createProfiler (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:158:26)
    at async Object.start (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:182:22)
```

`paymentservice`

```
Profiler enabled.
Tracing enabled.
Debugger enabled.
(node:1) [changeLevelName_deprecation] Warning: The changeLevelName option is deprecated and will be removed in v7. Use levelKey instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) [changeLevelName_deprecation] Warning: The changeLevelName option is deprecated and will be removed in v7. Use levelKey instead.
{"severity":"info","time":1673536399035,"pid":1,"hostname":"paymentservice-6d9b7cc6bf-kqjlc","name":"paymentservice-server","message":"PaymentService gRPC server started on port 50051","v":1}
/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120
        throw new Error('Project ID must be specified in the configuration');
              ^

Error: Project ID must be specified in the configuration
    at initConfigMetadata (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createProfiler (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:158:26)
    at async Object.start (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:182:22)
```

**To Reproduce**

1. `px demo deploy px-online-boutique`

**Expected behavior**

All pods should be in a Running state.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

**Logs**

Attached.

**App information (please complete the following information):**
- Pixie version: pem_image:0.12.10
- K8s cluster version: v1.22.16-eks-ffeb93d
- Node Kernel version: 5.4.226-129.415.amzn2.x86_64
- Browser version: N/A

**Additional context**

**Comment by htroisi** [comment]
It looks like this bug was fixed in https://github.com/GoogleCloudPlatform/microservices-demo/pull/665. We should update [our microservice-demo fork](https://github.com/pixie-io/microservices-demo) and see if this fixes things on EKS.

**Comment by htroisi** [comment]
The workaround is to uncomment all of the `DISABLE_*` env vars in https://github.com/pixie-io/pixie/blob/main/demos/online-boutique/online-boutique.yaml, then apply the file manually:

```
# Delete existing demo app
px demo delete px-online-boutique

# Manually deploy modified demo yaml
kubectl create ns px-online-boutique
kubectl apply -f online-boutique.yaml -n px-online-boutique
```
